# Generated by Django 4.2.25 on 2025-10-04 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('ficcao', 'Ficção'), ('nao_ficcao', 'Não-Ficção'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('biografia', 'Biografia'), ('tecnico', 'Técnico'), ('infantil', 'Infantil'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('isbn', models.CharField(max_length=17, unique=True, verbose_name='ISBN')),
                ('sinopse', models.TextField(blank=True, verbose_name='Sinopse')),
                ('editora', models.CharField(max_length=200, verbose_name='Editora')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa')),
                ('disponibilidade', models.BooleanField(default=True, verbose_name='Disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='catalogo.autor')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim_prevista', models.DateField(verbose_name='Data Prevista para Devolução')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='Data Real de Devolução')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado')], default='ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='catalogo.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
